<!-- /**
     * Autor: Cristian Enciso (Enciso_crida)
     * vista: sección registrar entrada/salida).
     *
     * 
     */ -->
     <div>

<form action="#">
<h1>ingreso</h1>
<input type="text" placeholder="Documento"> <br>
<!-- las ubicaciones ya estaran registradas en una tabla de la base de datos.
mediante una funcion, consulta etc. seran traidos e incluidos como una opcion para selecionar, 
las opciones puestas a continuacion son ejemplos nada mas -->
<select name="ubicacion">
    <option value="flase">select ubicacion</option>
   <option value="1">ubicacion 1</option> 
   <option value="2">ubicacion 2</option> 
   <option value="3">ubicacion 3</option>
   <option value="4">ubicacion 4</option> 
   <option value="5">ubicacion 5</option> 
   <option value="6">ubicacion 6</option> 
</select>

</form>


<br>


</div>

<div>
<h1>salida</h1>
<form action="#">
<input type="text" placeholder="Documento"><br>
<input type="submit" value="registrar">
</form>
</div>
