
            <ul class="nav"><!-- En esta parte se pueden editar y agregar más seccones al menú. HAy que cuidar la estructura. -->
            <li><a href="ubicacion.php">Ubicacion</a></li>
              <li><a href="usuarios.php">Usuarios</a></li>
              <li><a href="fichas.php">Fichas</a></li>
              <li><a href="reporte_usuario.php">reporte por usuario</a></li>
              <li><a href="reporte_ficha.php">reporte por ficha</a></li>
              <li><a href="reporte_ambiente.php">reporte por ambiente</a></li>
            </ul>