<!-- **
     * Autor: Cristian Enciso (Enciso_crida)
     * vista: sección registrar usuarios.
     *
     * 
     *-->

     <form action="../controlador/ubicacion(2).php" method="POST">

<input type="text" placeholder="Nombre de ubicacion" name="nombre">
<input type="text" placeholder="descripcion" name="descripcion">
<input type="number" placeholder="id sede" name="idSede">
<input type="submit" value="registrar">
</form>