<!-- **
     * Autor: Cristian Enciso (Enciso_crida)
     * vista: sección registrar sede
     *
     * 
     *-->

 <form action="../controlador/sede.php" method="POST">

<input type="text" placeholder="Nombre de sede" name="nombre">
<input type="text" placeholder="direccion" name="direccion">
<input type="text" placeholder="telefono" name="telefono">
<input type="submit" value="registrar">
</form>